# Generated by Django 6.0.2 on 2026-02-07 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0015_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'task_locks',
                'indexes': [models.Index(fields=['task_name', 'expires_at'], name='task_locks_task_na_e00a35_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('mou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mou.mou')),
            ],
            options={
                'db_table': 'email_logs',
                'indexes': [models.Index(fields=['-sent_at'], name='email_logs_sent_at_cde0c7_idx'), models.Index(fields=['task_name', '-sent_at'], name='email_logs_task_na_4c4f22_idx')],
            },
        ),
    ]
